### ISSUE TITLE
PaymentSetup PayPal Could not save payment information

### ISSUE THREAD

**Issue by lukeryb** [PartnerCenterSamples/Reseller-Web-Application#19]
Hi There, 

When we are trying to go through the three steps to setup the storefront, we are running into an issue trying to apply the paypal sandbox client id/client secret. 

We are getting an error "Could not save payment information". 

Is this a bug, if so how can we get this resolved? Can this be manually hard coded into a config file via ftp?

Thanks

**Comment by tameemansari** [comment]
This could happen primarily due to invalid client id / secret combination. The code makes a call to PayPal API before saving data to ensure that those credentials are applicable or not. 

To diagnose this deeper, you could use the kudu logstream url to collect logs / exceptions generated & logged on the server side. You can access the Kudu site for your storefront deployment at the following url. https://{nameofyoursite}.scm.azurewebsites.net/logstream - When prompted to login use the same credentials you used to login to the storefront admin site. 

Once you are logged in. In a different window please navigate to the Payment setup page of the storefront and retry saving. 

If you are able to collect the traces, please post them as a gist or in a reply to this issue for me to follow up. 

Thanks.

**Comment by lukeryb** [comment]
Hi, 
Thank you for your response. I am trying to navigate to the url as per your instructions, and it seems to not work. if I take out /logstream, I am able to view a Kudu environment which has options like Environment, Site extensions etc. When selecting anything within Tools, the pages seem not to load. 

As for the paypal details, I'm confused where there could be mismatch, since I've followed the correct instructions as per Paypals tutorials. I have created the accounts, and converted them to Business Pro, and created an App within Paypal sandbox, and assigned the account, which then I'm given a Client ID and a self generated Secret. 

Am I missing anything? 

When going through the logs in Azure (where the site is being hosted), I'm noticing there are errors related to not being able to access/write to directories? Does this make any sense? Are there any customer settings I need to adjust in the Azure Portal where the site is hosted? We were able to configure the branding, and offerings components without any issues. 

Thanks

**Comment by tameemansari** [comment]
Quick question did you deploy the site from Partner center or some other way?

**Comment by tameemansari** [comment]
Please verify the client id and secret you are typing in at the PayPal API playground too... https://devtools-paypal.com/hateoas/

**Comment by lukeryb** [comment]
We did deploy using partner center. We are not working through the three steps, last one being this paypal setup. 

I went to your link for paypal, and confirmed that our Client ID and Secret is working using their test API data. 

When accessing the log stream, here are the errors we are getting, at the time of trying to save the Paypal details. 

`
This error means that there was a problem while processing the request. The request was received by the Web server, but during processing a fatal error occurred, causing the 500 error. 
<p><a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=500,0,0x00000000,9200">View more information &raquo;</a></p> 
<p>Microsoft Knowledge Base Articles:</p> 

2016-12-23T14:19:13  PID[180] Error       ErrorHandler: Intercepted Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Store.PartnerCenter.CustomerPortal.BusinessLogic.Commerce.PaymentGateways.PayPalGateway.CreateWebExperienceProfile(PaymentConfiguration paymentConfig, BrandingConfiguration brandConfig, String countryIso2Code)
   at Microsoft.Store.PartnerCenter.CustomerPortal.Controllers.AdminConsoleController.<UpdatePaymentConfiguration>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext(). Returning 500 as response.`

**Comment by tameemansari** [comment]
Thanks for the stack trace. I understand what may be the issue here. You may have not yet setup the Header image in the branding page (they are not mandatory hence are allowed to be skipped). For now, before attempting to update the payment settings. Can you go add the header image in the portal branding section. After validating your PayPal settings, the store front creates a PayPal web experience profile (which uses your store front logo & header image) for the PayPal payment pages.  Once you save these two. Please go to the payment configuration and save. If this still throws errors please drop me a note at 'tansar' at Microsoft.com and we can debug this offline. 

This issue is fixed for the Dec/Jan release although I am going to try to fast track this fix asap. 

Hope this helps.

**Comment by tameemansari** [comment]
I have just done a fast track fix (https://github.com/PartnerCenterSamples/Reseller-Web-Application/pull/20) of this issue on the dev branch. If my above stated resolution works subsequently I will PR this to master.

**Comment by lukeryb** [comment]
So looks like once I applied a header in the customization, I was able to save my Paypal details. 

Seems to be working now.

**Comment by lukeryb** [comment]
Also once more questions, regarding offers, I notice the pricing is stating Annual. Are these not priced via monthly per seat?

**Comment by tameemansari** [comment]
Thanks for the confirmation. 

Pricing is managed annually on the store front. Prorated calculation are done on a yearly basis too when the customer adds seats to an existing store front subscription. Please take care of pricing the offers in your store front configuration on a yearly basis. 

I will closing this issue at this time.
